### ISSUE TITLE
Unable to load FFProbe

### ISSUE THREAD

**Issue by deadpool8426** [pawlox/video-thumbnail#9]
I am working with laravel 5.8 and try to generate a video thumbnail and get this error regularly. I have run php artisan config:clear and composer dumpautoload but I am getting this error again and again. Please resolve this issue ASAP.

[2021-06-07 22:42:36] local.ERROR: Unable to load FFProbe {"userId":1,"exception":"[object] (FFMpeg\\Exception\\ExecutableNotFoundException(code: 0): Unable to load FFProbe at /var/home/aabhushn/restaurant.aabhushnam.com/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/Driver/FFProbeDriver.php:50, Alchemy\\BinaryDriver\\Exception\\ExecutableNotFoundException(code: 0): Executable not found, proposed : /usr/bin/ffprobe at /var/home/aabhushn/restaurant.aabhushnam.com/vendor/alchemy/binary-driver/src/Alchemy/BinaryDriver/AbstractBinary.php:159)
[stacktrace]
#0 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFProbe.php(226): FFMpeg\\Driver\\FFProbeDriver::create(Object(Alchemy\\BinaryDriver\\Configuration), NULL)
#1 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/php-ffmpeg/php-ffmpeg/src/FFMpeg/FFMpeg.php(132): FFMpeg\\FFProbe::create(Array, NULL, Object(Doctrine\\Common\\Cache\\ArrayCache))
#2 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/spatie/laravel-medialibrary/src/ImageGenerators/FileTypes/Video.php(19): FFMpeg\\FFMpeg::create(Array)
#3 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(95): Spatie\\MediaLibrary\\ImageGenerators\\FileTypes\\Video->convert('/var/home/aabhu...', Object(Spatie\\MediaLibrary\\Conversion\\Conversion))
#4 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Support/Collection.php(475): Spatie\\MediaLibrary\\FileManipulator->Spatie\\MediaLibrary\\{closure}(Object(Spatie\\MediaLibrary\\Conversion\\Conversion), 0)
#5 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(116): Illuminate\\Support\\Collection->each(Object(Closure))
#6 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/spatie/laravel-medialibrary/src/Jobs/PerformConversions.php(37): Spatie\\MediaLibrary\\FileManipulator->performConversions(Object(Spatie\\MediaLibrary\\Conversion\\ConversionCollection), Object(App\\Models\\Media), false)
#7 [internal function]: Spatie\\MediaLibrary\\Jobs\\PerformConversions->handle()
#8 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(32): call_user_func_array(Array, Array)
#9 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(90): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#10 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(34): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#11 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Container/Container.php(576): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#12 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(94): Illuminate\\Container\\Container->call(Array)
#13 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(128): Illuminate\\Bus\\Dispatcher->Illuminate\\Bus\\{closure}(Object(Spatie\\MediaLibrary\\Jobs\\PerformConversions))
#14 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Spatie\\MediaLibrary\\Jobs\\PerformConversions))
#15 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(98): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#16 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Queue/CallQueuedHandler.php(49): Illuminate\\Bus\\Dispatcher->dispatchNow(Object(Spatie\\MediaLibrary\\Jobs\\PerformConversions), false)
#17 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php(88): Illuminate\\Queue\\CallQueuedHandler->call(Object(Illuminate\\Queue\\Jobs\\SyncJob), Array)
#18 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Queue/SyncQueue.php(42): Illuminate\\Queue\\Jobs\\Job->fire()
#19 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(184): Illuminate\\Queue\\SyncQueue->push(Object(Spatie\\MediaLibrary\\Jobs\\PerformConversions))
#20 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(160): Illuminate\\Bus\\Dispatcher->pushCommandToQueue(Object(Illuminate\\Queue\\SyncQueue), Object(Spatie\\MediaLibrary\\Jobs\\PerformConversions))
#21 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Bus/Dispatcher.php(73): Illuminate\\Bus\\Dispatcher->dispatchToQueue(Object(Spatie\\MediaLibrary\\Jobs\\PerformConversions))
#22 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(156): Illuminate\\Bus\\Dispatcher->dispatch(Object(Spatie\\MediaLibrary\\Jobs\\PerformConversions))
#23 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/spatie/laravel-medialibrary/src/FileManipulator.php(50): Spatie\\MediaLibrary\\FileManipulator->dispatchQueuedConversions(Object(App\\Models\\Media), Object(Spatie\\MediaLibrary\\Conversion\\ConversionCollection), false)
#24 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/spatie/laravel-medialibrary/src/Filesystem/Filesystem.php(35): Spatie\\MediaLibrary\\FileManipulator->createDerivedFiles(Object(App\\Models\\Media))
#25 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php(378): Spatie\\MediaLibrary\\Filesystem\\Filesystem->add('/tmp/phpfBt8DG', Object(App\\Models\\Media), 'vid-20210607153...')
#26 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php(364): Spatie\\MediaLibrary\\FileAdder\\FileAdder->processMediaItem(Object(App\\Models\\Upload), Object(App\\Models\\Media), Object(Spatie\\MediaLibrary\\FileAdder\\FileAdder))
#27 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/spatie/laravel-medialibrary/src/FileAdder/FileAdder.php(314): Spatie\\MediaLibrary\\FileAdder\\FileAdder->attachMedia(Object(App\\Models\\Media))
#28 /var/home/aabhushn/restaurant.aabhushnam.com/app/Http/Controllers/UploadController.php(86): Spatie\\MediaLibrary\\FileAdder\\FileAdder->toMediaCollection('video')
#29 [internal function]: App\\Http\\Controllers\\UploadController->store(Object(App\\Http\\Requests\\UploadRequest))
#30 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Controller.php(54): call_user_func_array(Array, Array)
#31 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(45): Illuminate\\Routing\\Controller->callAction('store', Array)
#32 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(219): Illuminate\\Routing\\ControllerDispatcher->dispatch(Object(Illuminate\\Routing\\Route), Object(App\\Http\\Controllers\\UploadController), 'store')
#33 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Route.php(176): Illuminate\\Routing\\Route->runController()
#34 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(680): Illuminate\\Routing\\Route->run()
#35 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Routing\\Router->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#36 /var/home/aabhushn/restaurant.aabhushnam.com/app/Http/Middleware/RestrictIp.php(31): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\RestrictIp->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#38 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#39 /var/home/aabhushn/restaurant.aabhushnam.com/app/Http/Middleware/Permissions.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#40 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\Permissions->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#41 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#42 /var/home/aabhushn/restaurant.aabhushnam.com/app/Http/Middleware/App.php(46): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#43 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\App->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#44 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#45 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/anlutro/l4-settings/src/SaveMiddleware.php(45): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): anlutro\\LaravelSettings\\SaveMiddleware->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(41): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#49 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Routing\\Middleware\\SubstituteBindings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#50 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#51 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(75): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\VerifyCsrfToken->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#53 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#54 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/AuthenticateSession.php(58): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#55 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\AuthenticateSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#56 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#57 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Auth/Middleware/Authenticate.php(43): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#58 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Auth\\Middleware\\Authenticate->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#59 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#60 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#61 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\View\\Middleware\\ShareErrorsFromSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#62 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#63 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(56): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#64 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#65 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#66 /var/home/aabhushn/restaurant.aabhushnam.com/app/Http/Middleware/Installed.php(29): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#67 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): App\\Http\\Middleware\\Installed->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#68 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#69 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#70 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#71 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#72 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(66): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#73 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#74 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#75 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#76 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(682): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#77 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(657): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#78 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(623): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#79 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Router.php(612): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#80 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(176): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#81 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(30): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#82 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/barryvdh/laravel-debugbar/src/Middleware/InjectDebugbar.php(65): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#83 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Barryvdh\\Debugbar\\Middleware\\InjectDebugbar->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#84 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#85 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/fideloper/proxy/src/TrustProxies.php(57): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#86 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Fideloper\\Proxy\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#87 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#88 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#89 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#90 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#91 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#92 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#93 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#94 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#95 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#96 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#97 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/CheckForMaintenanceMode.php(62): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#98 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(163): Illuminate\\Foundation\\Http\\Middleware\\CheckForMaintenanceMode->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#99 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Routing/Pipeline.php(53): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#100 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(104): Illuminate\\Routing\\Pipeline->Illuminate\\Routing\\{closure}(Object(Illuminate\\Http\\Request))
#101 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(151): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#102 /var/home/aabhushn/restaurant.aabhushnam.com/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(116): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#103 /var/home/aabhushn/restaurant.aabhushnam.com/public/index.php(57): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#104 {main}
"}

**Comment by divyesh-zignuts** [comment]
Hello connection,
I'm trying to generate video thumbnail using this package but getting error something like this:

`local.ERROR: Unable to probe http://localhost/storage/5/1/property-videos/file_example_MP4_480_1_5MG.mp4`

If any one have relevant solution then it would be appreciate.
Thanks in advance.

**Comment by pawel-marciniak** [comment]
I think you have wrong path to file, looks like url but it should be absolute path in filesystem.

**Comment by divyesh-zignuts** [comment]
> I think you have wrong path to file, looks like url but it should be absolute path in filesystem.

But, I can see "file_example_MP4_480_1_5MG.mp4" file in the same path.

**Comment by pawel-marciniak** [comment]
Yep, but this package is using CLI (terminal) tools (ffmpeg), and if this tool don't support urls (only file paths like /usr/local/somefile.mp4) it won't work. This is just my guess, maybe it's something else.
